In [1]:
import pandas as pd
import numpy as np
import nltk
import gensim
import gensim.downloader as gensim_api

import re

## for plotting
import matplotlib.pyplot as plt
import seaborn as sns


C:\Users\karth\anaconda3\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)


In [2]:
#loading the train and the test data
train = pd.read_csv("C:/Users/karth/Desktop/Dissertation/Data/AG_news_train.csv")
test = pd.read_csv("C:/Users/karth/Desktop/Dissertation/Data/AG_news_test.csv")
frames = [train,test]
data = pd.concat(frames)
data

Class Index                                              Title  \
0               3  Wall St. Bears Claw Back Into the Black (Reuters)   
1               3  Carlyle Looks Toward Commercial Aerospace (Reu...   
2               3    Oil and Economy Cloud Stocks' Outlook (Reuters)   
3               3  Iraq Halts Oil Exports from Main Southern Pipe...   
4               3  Oil prices soar to all-time record, posing new...   
...           ...                                                ...   
7595            1                                   Around the world   
7596            2                        Void is filled with Clement   
7597            2                             Martinez leaves bitter   
7598            3  5 of arthritis patients in Singapore take Bext...   
7599            3                             EBay gets into rentals   

                                            Description  
0     Reuters - Short-sellers, Wall Street's dwindli...  
1     Reuters - Private investment firm Carlyle Grou...  
2     Reuters - Soaring crude prices plus worries\ab...  
3     Reuters - Authorities have halted oil export\f...  
4     AFP - Tearaway world oil prices, toppling reco...  
...                                                 ...  
7595  Ukrainian presidential candidate Viktor Yushch...  
7596  With the supply of attractive pitching options...  
7597  Like Roger Clemens did almost exactly eight ye...  
7598  SINGAPORE : Doctors in the United States have ...  
7599  EBay plans to buy the apartment and home renta...  

[127600 rows x 3 columns]

In [3]:
data['Class Index'] = data['Class Index'].astype('str')
classes = {"1" : "World",
                     "2" : "Sports",
                     "3" : "Business",
                     "4" : "Sci&Tech"}

data['Class'] = data['Class Index'].map(classes)
data

Class Index                                              Title  \
0              3  Wall St. Bears Claw Back Into the Black (Reuters)   
1              3  Carlyle Looks Toward Commercial Aerospace (Reu...   
2              3    Oil and Economy Cloud Stocks' Outlook (Reuters)   
3              3  Iraq Halts Oil Exports from Main Southern Pipe...   
4              3  Oil prices soar to all-time record, posing new...   
...          ...                                                ...   
7595           1                                   Around the world   
7596           2                        Void is filled with Clement   
7597           2                             Martinez leaves bitter   
7598           3  5 of arthritis patients in Singapore take Bext...   
7599           3                             EBay gets into rentals   

                                            Description     Class  
0     Reuters - Short-sellers, Wall Street's dwindli...  Business  
1     Reuters - Private investment firm Carlyle Grou...  Business  
2     Reuters - Soaring crude prices plus worries\ab...  Business  
3     Reuters - Authorities have halted oil export\f...  Business  
4     AFP - Tearaway world oil prices, toppling reco...  Business  
...                                                 ...       ...  
7595  Ukrainian presidential candidate Viktor Yushch...     World  
7596  With the supply of attractive pitching options...    Sports  
7597  Like Roger Clemens did almost exactly eight ye...    Sports  
7598  SINGAPORE : Doctors in the United States have ...  Business  
7599  EBay plans to buy the apartment and home renta...  Business  

[127600 rows x 4 columns]

In [4]:
def text_preprocessing(text, flag_stemm=False, flag_lemma=True, lst_stopwords=None):
    ## clean (convert to lowercase and remove punctuations and characters and then strip)
    text = re.sub(r'[^\w\s]', '', str(text).lower().strip())
            
    ## Tokenize (convert from string to list)
    lst_text = text.split()
    ## remove Stopwords
    if lst_stopwords is not None:
        lst_text = [word for word in lst_text if word not in 
                    lst_stopwords]
                
    ## Stemming (remove -ing, -ly, ...)
    if flag_stemm == True:
        ps = nltk.stem.porter.PorterStemmer()
        lst_text = [ps.stem(word) for word in lst_text]
                
    ## Lemmatisation (convert the word into root word)
    if flag_lemma == True:
        lem = nltk.stem.wordnet.WordNetLemmatizer()
        lst_text = [lem.lemmatize(word) for word in lst_text]
            
    ## back to string from list
    text = " ".join(lst_text)
    return text

lst_stopwords = nltk.corpus.stopwords.words("english")

In [5]:
##applying the text preprocessing function created to the entire dataset
data["cleaned_text"] = data["Description"].apply(lambda x: text_preprocessing(x, flag_stemm=False, flag_lemma=True, lst_stopwords=lst_stopwords))
data.head()

Class Index                                              Title  \
0           3  Wall St. Bears Claw Back Into the Black (Reuters)   
1           3  Carlyle Looks Toward Commercial Aerospace (Reu...   
2           3    Oil and Economy Cloud Stocks' Outlook (Reuters)   
3           3  Iraq Halts Oil Exports from Main Southern Pipe...   
4           3  Oil prices soar to all-time record, posing new...   

                                         Description     Class  \
0  Reuters - Short-sellers, Wall Street's dwindli...  Business   
1  Reuters - Private investment firm Carlyle Grou...  Business   
2  Reuters - Soaring crude prices plus worries\ab...  Business   
3  Reuters - Authorities have halted oil export\f...  Business   
4  AFP - Tearaway world oil prices, toppling reco...  Business   

                                        cleaned_text  
0  reuters shortsellers wall street dwindlingband...  
1  reuters private investment firm carlyle groupw...  
2  reuters soaring crude price plus worriesabout ...  
3  reuters authority halted oil exportflows main ...  
4  afp tearaway world oil price toppling record s...

In [6]:
data['Class'].value_counts()

Business    31900
Sports      31900
Sci&Tech    31900
World       31900
Name: Class, dtype: int64

In [7]:
data_sample = data.groupby('Class').apply(lambda x: x.sample(n=2500)).reset_index(drop = True)
data_sample['Class'].value_counts()

Sports      2500
Business    2500
World       2500
Sci&Tech    2500
Name: Class, dtype: int64

In [8]:
# Importing libraries
import os
import sys
import numpy as np
import keras
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Activation, Conv2D, Input, Embedding, Reshape, MaxPool2D, Concatenate, Flatten, Dropout, Dense, Conv1D
from keras.layers import MaxPool1D
from keras.models import Model
from keras.callbacks import ModelCheckpoint
from tensorflow.keras.optimizers import Adam

In [9]:
texts = data_sample["cleaned_text"]
labels = data_sample.iloc[:, 0].astype(str)
tokenizer  = Tokenizer(num_words = MAX_WORDS)
tokenizer.fit_on_texts(texts)
sequences =  tokenizer.texts_to_sequences(texts)

word_index = tokenizer.word_index
print("unique words : {}".format(len(word_index)))

data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)

labels = to_categorical(np.asarray(labels))
print('Shape of data tensor:', data.shape)
print('Shape of label tensor:', labels.shape)
print(labels)

NameError: name 'MAX_WORDS' is not defined

In [163]:
# split the data into a training set and a validation set
indices = np.arange(data.shape[0])
np.random.shuffle(indices)
data = data[indices]
labels = labels[indices]
nb_validation_samples = int(VALIDATION_SPLIT * data.shape[0])

x_train = data[:-nb_validation_samples]
y_train = labels[:-nb_validation_samples]
x_val = data[-nb_validation_samples:]
y_val = labels[-nb_validation_samples:]

In [164]:
import gensim
from gensim.models import Word2Vec
from gensim.utils import simple_preprocess

from gensim.models.keyedvectors import KeyedVectors
PATH = 'C:/Users/karth/Desktop/Dissertation/Code'
word_vectors = KeyedVectors.load_word2vec_format(PATH+'/GoogleNews-vectors-negative300.bin', binary=True)

EMBEDDING_DIM=300
vocabulary_size=min(len(word_index)+1,NUM_WORDS)
embedding_matrix = np.zeros((vocabulary_size, EMBEDDING_DIM))
for word, i in word_index.items():
    if i>=NUM_WORDS:
        continue
    try:
        embedding_vector = word_vectors[word]
        embedding_matrix[i] = embedding_vector
    except KeyError:
        embedding_matrix[i]=np.random.normal(0,np.sqrt(0.25),EMBEDDING_DIM)
        


In [ ]:
W2V_PATH = 'C:/Users/karth/Desktop/Dissertation/Code/'
embeddings_index = {}
f = open(os.path.join(W2V_PATH, 'glove.6B.100d.txt'),encoding="utf8")
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

print('Found %s word vectors.' % len(embeddings_index))

In [ ]:
# make the max word length to be constant
MAX_WORDS = 10000
MAX_SEQUENCE_LENGTH = embedding_matrix.shape[1]
# the percentage of train test split to be applied
VALIDATION_SPLIT = 0.20
# the dimension of vectors to be used
EMBEDDING_DIM = 300
# filter sizes of the different conv layers 
filter_sizes = [3,4,5]
num_filters = 512
embedding_dim = 300
# dropout probability
drop = 0.5
batch_size = 100
epochs = 5

In [165]:
from keras.layers import Embedding
embedding_layer = Embedding(len(word_index) + 1,
                            EMBEDDING_DIM,
                            weights=[embedding_matrix],
                            input_length=MAX_SEQUENCE_LENGTH,
                            trainable=False)

In [166]:
MAX_SEQUENCE_LENGTH

1000

In [167]:
inputs = Input(shape=(MAX_SEQUENCE_LENGTH,), dtype='int32')
embedding = embedding_layer(inputs)

print(embedding.shape)
reshape = Reshape((MAX_SEQUENCE_LENGTH,EMBEDDING_DIM,1))(embedding)
print(reshape.shape)

conv_0 = Conv2D(num_filters, kernel_size=(filter_sizes[0], embedding_dim), padding='valid', kernel_initializer='normal', activation='relu')(reshape)
conv_1 = Conv2D(num_filters, kernel_size=(filter_sizes[1], embedding_dim), padding='valid', kernel_initializer='normal', activation='relu')(reshape)
conv_2 = Conv2D(num_filters, kernel_size=(filter_sizes[2], embedding_dim), padding='valid', kernel_initializer='normal', activation='relu')(reshape)

maxpool_0 = MaxPool2D(pool_size=(MAX_SEQUENCE_LENGTH - filter_sizes[0] + 1, 1), strides=(1,1), padding='valid')(conv_0)
maxpool_1 = MaxPool2D(pool_size=(MAX_SEQUENCE_LENGTH - filter_sizes[1] + 1, 1), strides=(1,1), padding='valid')(conv_1)
maxpool_2 = MaxPool2D(pool_size=(MAX_SEQUENCE_LENGTH - filter_sizes[2] + 1, 1), strides=(1,1), padding='valid')(conv_2)

concatenated_tensor = Concatenate(axis=1)([maxpool_0, maxpool_1, maxpool_2])
flatten = Flatten()(concatenated_tensor)
dropout = Dropout(drop)(flatten)
output = Dense(units=5, activation='softmax')(dropout)

# this creates a model that includes
model = Model(inputs=inputs, outputs=output)

checkpoint = ModelCheckpoint('weights_cnn_sentece.hdf5', monitor='val_acc', verbose=1, save_best_only=True, mode='auto')
adam = Adam(lr=1e-4, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)

model.compile(optimizer=adam, loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

ValueError: Layer embedding_13 weight shape (24485, 300) is not compatible with provided weight shape (20000, 300).

In [74]:
print("Traning Model...")
model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1, callbacks=[checkpoint], validation_data=(x_val, y_val))

Traning Model...
Epoch 1/5
4/4 [==============================] - 235s 51s/step - loss: 2.1165 - accuracy: 0.2288 - val_loss: 1.5391 - val_accuracy: 0.3050
Epoch 2/5
4/4 [==============================] - 226s 55s/step - loss: 1.8040 - accuracy: 0.2894 - val_loss: 1.4164 - val_accuracy: 0.3575
Epoch 3/5
4/4 [==============================] - 233s 55s/step - loss: 1.6752 - accuracy: 0.3131 - val_loss: 1.3386 - val_accuracy: 0.3900
Epoch 4/5
4/4 [==============================] - 216s 51s/step - loss: 1.6356 - accuracy: 0.3100 - val_loss: 1.2773 - val_accuracy: 0.4375
Epoch 5/5
4/4 [==============================] - 270s 63s/step - loss: 1.5161 - accuracy: 0.3525 - val_loss: 1.2148 - val_accuracy: 0.4925


In [103]:
# make the max word length to be constant
MAX_WORDS = 10000
MAX_SEQUENCE_LENGTH = 1000
# the percentage of train test split to be applied
VALIDATION_SPLIT = 0.20
# the dimension of vectors to be used
EMBEDDING_DIM = 300
# filter sizes of the different conv layers 
filter_sizes = [3,4,5]
num_filters = 512
embedding_dim = 300
# dropout probability
drop = 0.5
batch_size = 500
epochs = 5

In [98]:
texts = data_sample["cleaned_text"]
labels = data_sample.iloc[:, 0].astype(str)
tokenizer  = Tokenizer(num_words = MAX_WORDS)
tokenizer.fit_on_texts(texts)
sequences =  tokenizer.texts_to_sequences(texts)

word_index = tokenizer.word_index
print("unique words : {}".format(len(word_index)))

data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)

labels = to_categorical(np.asarray(labels))
print('Shape of data tensor:', data.shape)
print('Shape of label tensor:', labels.shape)
print(labels)

unique words : 49867
Shape of data tensor: (40000, 1000)
Shape of label tensor: (40000, 5)
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [99]:
# split the data into a training set and a validation set
indices = np.arange(data.shape[0])
np.random.shuffle(indices)
data = data[indices]
labels = labels[indices]
nb_validation_samples = int(VALIDATION_SPLIT * data.shape[0])

x_train = data[:-nb_validation_samples]
y_train = labels[:-nb_validation_samples]
x_val = data[-nb_validation_samples:]
y_val = labels[-nb_validation_samples:]

In [100]:
GLOVE_DIR = 'C:/Users/karth/Desktop/Dissertation/Code/'
embeddings_index = {}
f = open(os.path.join(GLOVE_DIR, 'glove.6B.100d.txt'),encoding="utf8")
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

print('Found %s word vectors.' % len(embeddings_index))

Found 400000 word vectors.


In [104]:
from keras.layers import Embedding

embedding_layer = Embedding(len(word_index) + 1,
                            EMBEDDING_DIM,
                            weights=[embedding_matrix],
                            input_length=MAX_SEQUENCE_LENGTH,
                            trainable=False)

In [105]:
inputs = Input(shape=(MAX_SEQUENCE_LENGTH,), dtype='int32')
embedding = embedding_layer(inputs)

print(embedding.shape)
reshape = Reshape((MAX_SEQUENCE_LENGTH,EMBEDDING_DIM,1))(embedding)
print(reshape.shape)

conv_0 = Conv2D(num_filters, kernel_size=(filter_sizes[0], embedding_dim), padding='valid', kernel_initializer='normal', activation='relu')(reshape)
conv_1 = Conv2D(num_filters, kernel_size=(filter_sizes[1], embedding_dim), padding='valid', kernel_initializer='normal', activation='relu')(reshape)
conv_2 = Conv2D(num_filters, kernel_size=(filter_sizes[2], embedding_dim), padding='valid', kernel_initializer='normal', activation='relu')(reshape)

maxpool_0 = MaxPool2D(pool_size=(MAX_SEQUENCE_LENGTH - filter_sizes[0] + 1, 1), strides=(1,1), padding='valid')(conv_0)
maxpool_1 = MaxPool2D(pool_size=(MAX_SEQUENCE_LENGTH - filter_sizes[1] + 1, 1), strides=(1,1), padding='valid')(conv_1)
maxpool_2 = MaxPool2D(pool_size=(MAX_SEQUENCE_LENGTH - filter_sizes[2] + 1, 1), strides=(1,1), padding='valid')(conv_2)

concatenated_tensor = Concatenate(axis=1)([maxpool_0, maxpool_1, maxpool_2])
flatten = Flatten()(concatenated_tensor)
dropout = Dropout(drop)(flatten)
output = Dense(units=5, activation='softmax')(dropout)

# this creates a model that includes
model = Model(inputs=inputs, outputs=output)

checkpoint = ModelCheckpoint('weights_cnn_sentece.hdf5', monitor='val_acc', verbose=1, save_best_only=True, mode='auto')
adam = Adam(lr=1e-4, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)

model.compile(optimizer=adam, loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

ValueError: Layer embedding_6 weight shape (49868, 300) is not compatible with provided weight shape (20000, 300).

In [81]:
print("Traning Model...")
model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1, callbacks=[checkpoint], validation_data=(x_val, y_val))

Traning Model...
Epoch 1/5
4/4 [==============================] - 251s 60s/step - loss: 2.1191 - accuracy: 0.1963 - val_loss: 1.5061 - val_accuracy: 0.2875
Epoch 2/5
4/4 [==============================] - 260s 63s/step - loss: 1.8102 - accuracy: 0.2650 - val_loss: 1.3913 - val_accuracy: 0.3675
Epoch 3/5
4/4 [==============================] - 252s 57s/step - loss: 1.6634 - accuracy: 0.3044 - val_loss: 1.3309 - val_accuracy: 0.4100
Epoch 4/5
4/4 [==============================] - 228s 53s/step - loss: 1.5820 - accuracy: 0.3369 - val_loss: 1.2749 - val_accuracy: 0.4400
Epoch 5/5
4/4 [==============================] - 232s 55s/step - loss: 1.5328 - accuracy: 0.3619 - val_loss: 1.2200 - val_accuracy: 0.5150
